//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IBA.rc
//
#define IDC_BUTTON_RETURN               3
#define IDD_JXC_EXCHANGE                102
#define IDR_MAINFRAME                   127
#define IDS_BT_NOT_PC                   128
#define IDS_COMPUTERLIST                129
#define IDR_CONTEXT_MENU                130
#define IDS_NETBARSEAT                  130
#define IDR_COMPUTER_MENU               130
#define IDR_POPUP_TOOLBAR               131
#define IDS_STANDARD                    131
#define IDS_COSTOM                      132
#define IDS_SYSMSG                      133
#define IDS_QUICKNOTES                  134
#define IDS_FASTLANE                    135
#define IDS_MAN                         136
#define IDS_WOMAN                       137
#define IDS_PAYTYPE1                    138
#define IDS_PAYTYPE2                    139
#define IDS_PAYTYPE0                    140
#define IDS_COMPUTERLISTHEADER          141
#define IDS_TERMONLINE                  142
#define IDS_TERMOFFLINE                 143
#define IDS_TERMLOCKED                  144
#define IDS_TERMLITTERMONEY             145
#define IDS_TERMTHIEF                   146
#define IDS_TERMSUSPEND                 147
#define IDS_TERMBIRTHDAY                148
#define IDS_TERMVIP                     149
#define IDS_TERMBLACK                   150
#define IDB_TOOLBAR256                  151
#define IDS_TERMNORECORD                151
#define IDS_TERMCONFLICT                152
#define IDS_TERMUNLOCK                  153
#define IDD_DIALOG_LOGIN                154
#define IDS_SELTERMS                    154
#define IDR_FASTLANE                    155
#define IDS_ALLTERMS                    155
#define IDS_ALLCASHIER                  156
#define IDD_DIALOG_SHORTMSG             157
#define IDS_RELPYMSG                    157
#define IDR_QUICKMSG_MENU               158
#define IDS_FORMTERMIP                  158
#define IDS_CLIENTINFO                  159
#define IDS_CASHIERINFO                 160
#define IDD_ND_REGISTER                 160
#define IDS_TOOLTIPHEADER               161
#define IDD_ND_REGISTER_PASSWORD        161
#define IDS_INPUTACCOUNT                162
#define IDD_ND_CREDITANDDEREG           162
#define IDS_LOGINERROR                  163
#define IDD_ND_MODIFYPWD                163
#define IDS_MACERROR                    164
#define IDS_NETFAILED                   165
#define IDD_DIALOG_ABOUT                165
#define IDS_INPUTERROR                  166
#define IDS_REGRESULT                   167
#define IDS_MONEYERROR                  168
#define IDS_HASUSED                     169
#define IDD_DIALOG_OFFDUTY              169
#define IDD_DUTY                        169
#define IDS_HASNOTUSED                  170
#define IDR_MENU1                       170
#define IDR_MENU_COLUMN                 170
#define IDS_IBATITLE                    171
#define IDS_CREDITRESULT                172
#define IDD_ND_CREDITANDDEREGREVERSE    172
#define IDD_ND_CREDITREVERSE            172
#define IDS_CREDITQUESTION              173
#define IDS_DREGRESULT                  174
#define IDS_DREGQUESTION                175
#define IDS_ONLINECREDIT                176
#define IDS_STATUSTEXT                  177
#define IDS_LOCALNETBAR                 178
#define IDS_STATTEXT                    179
#define IDS_DISCONNECT                  180
#define IDS_OPERATELOG                  181
#define IDS_STATINFO                    182
#define IDS_REGLOG                      183
#define IDS_MEMBERINFOLISTHEAD          183
#define IDS_CREDITLOG                   184
#define IDS_NOTHING                     184
#define IDS_ONLINECREDITLOG             185
#define IDS_REGBUNDLETIMELOG            185
#define IDS_MAXMONEY                    185
#define IDS_DREGLOG                     186
#define IDS_PAYOUT3                     186
#define IDS_SHUTDOWNQUESTION            187
#define IDS_OFFDUTYOK                   188
#define IDS_ONDUTYOK                    189
#define IDS_NOTONDUTY                   190
#define IDS_CREDITRLISTHEAD             191
#define IDS_EXITQUESTION                192
#define IDB_USERIMAGES                  193
#define IDS_USERINFO                    193
#define IDD_DIALOG_IBASET               194
#define IDS_IBASET                      194
#define IDD_SET_IBA                     194
#define IDS_EXITBOSSMODE                195
#define IDD_DIALOG_BOSSPWD              195
#define IDS_PARAMERROR                  195
#define IDS_PWDWRONG                    196
#define IDD_SET_MONITORCOLOR            197
#define IDS_MORE                        197
#define IDS_NOSAMLE                     198
#define IDS_MODIFYPWDSUCCESS            199
#define IDD_ND_MODIFYMEMBER             199
#define IDS_MODIFYPWDFAILE              200
#define IDD_ND_BUNDLETIME               200
#define IDS_MSGBOXFONT                  201
#define IDD_ND_CHANGEUSERSN             201
#define IDS_BUNDLETIMEINFO              201
#define IDS_INBOSSMODE                  202
#define IDS_CREDITRESULT2               202
#define IDD_SET_REGISTER                202
#define IDS_PAYOUT                      203
#define IDS_MODIFYMEMBERINFOSUCCESS     204
#define IDS_BUNDLETIMETYPE              205
#define IDD_CONFIG_CLIENT               205
#define IDS_BTSUCCESSED                 206
#define IDS_NOLIMITAREA                 207
#define IDD_NETBARINFO                  207
#define IDS_BTCANCELOK                  208
#define IDD_NETBAROTHERINFO             208
#define IDS_OPERATEOK                   209
#define IDD_BUNDLETINE_LISTDLG          209
#define IDS_OPREATEFAILED               210
#define IDS_SNNOLONG                    211
#define IDS_CANCELBUNDLETIME            212
#define IDS_ASKBUNDLETIME               213
#define IDS_NETBARCONFIG                214
#define IDD_ND_UPGRADE                  214
#define IDS_NETBARTYPE                  215
#define IDD_ND_CARDCREDIT               215
#define IDS_REGWINHTTPDLL               216
#define IDS_SYNCFAILED                  217
#define IDR_MENU_SCAN                   217
#define IDS_CONFIGLISTHEADER            218
#define IDS_REBOOTQUESTION              219
#define IDS_SCANFAILED                  220
#define IDS_CREDITREVERSE               221
#define IDS_USERONLINE                  222
#define IDS_BTINFO                      223
#define IDB_TOOLBARLARGE                223
#define IDS_INPUTCONDITION              224
#define IDS_CONSUMELSITHEADER           225
#define IDS_NORECORD                    226
#define IDS_TERMCONSUMELISTHEADER       227
#define IDS_SHIFTCASHHEADER             228
#define IDV_TERMCONSUME                 229
#define IDS_JXCQUERYRESULT              229
#define IDS_REMOTECHECKOUTFIALED        230
#define IDV_OPERATION                   230
#define IDS_FORCERETURN                 231
#define IDS_REGBUNDLETIME               232
#define IDV_SHIFTCASH                   232
#define IDS_ERRORUSERNAME               233
#define IDV_CONSUMELIST                 233
#define IDS_IDNUMERROR                  234
#define IDS_REGSUCCESS                  235
#define IDS_CASHREGISTERID              235
#define IDD_REALNAMECONFIG              235
#define IDS_INPUTCERTIFICATENUM         236
#define IDD_JXC                         236
#define IDS_INPUTNETID                  237
#define IDD_JXC_SELLDLG                 237
#define IDS_TERMCONSUME                 238
#define IDD_MSGBOXDLG                   238
#define IDS_TERMCONSUMERESULT           239
#define IDD_JXC_COMMODITY               239
#define IDS_OPERATIONQUERY              240
#define IDS_SHIFTCASHQUERYRESULT        241
#define IDD_JXC_RETURNDLG               241
#define IDS_SHIFICASHQUERY              242
#define IDD_JXC_VOUCHERNO               242
#define IDS_CONSUMELISTQUERY            243
#define IDD_JXC_QUERYDLG                243
#define IDS_CONSUMELISTQUERYRESULT      244
#define IDS_CONSUMETYPE                 245
#define IDS_CONNETCTDBFIALED            246
#define IDS_CREDITRESERVEROK            247
#define IDD_SET_JXC                     247
#define IDS_DONOTONDUTY                 248
#define IDD_SET_TTS                     248
#define IDS_SYNCOK                      249
#define IDD_RN_REGIMAGEDLG              249
#define IDS_SHIFTNAME                   250
#define IDS_BTCANCELOK2                 250
#define IDS_LOGINFOLISTGHEADER          251
#define IDD_RN_CHECKMEMBER              251
#define IDS_DOONDUTY                    252
#define IDD_JXC_POINT                   252
#define IDS_DUTYJXC                     253
#define IDD_DIALOG_AGENT                253
#define IDS_DOSTAT                      254
#define IDD_DIALOG_SEATSET              254
#define IDD_SET_SEAT                    254
#define IDS_NOCOMMODITY                 255
#define IDR_POPUP_SEATZOOM              255
#define IDS_TTSTEST                     256
#define IDD_SEAT_ADDTERMINAL            256
#define IDS_CONNETPROYERROR             257
#define IDS_JXCQUERYHEADER              258
#define IDR_POPUP_SEATEDIT              258
#define IDS_UPGRADELOG                  259
#define IDS_ONLINECREDITREVERSE         260
#define ID_SEAT_TERMINALINFO            261
#define IDS_MUTIREFUNDRESULT            262
#define IDS_NOMUTIREFUND                263
#define IDS_ERRORBCCS                   263
#define IDS_CONFORMREFUND               264
#define IDS_REFUNDLISTHEAD              265
#define IDS_ACTIVELOG                   266
#define IDS_CARDACTIVELOG               267
#define IDS_LOGACTIVELISTGHEADER        268
#define IDD_DIALOG_MEMBERINFO           268
#define IDS_REGISTERINFO                269
#define IDM_LOCAL_EXITIBA               270
#define IDD_JXC_PRESENT                 271
#define IDS_POINT                       271
#define IDD_DUTY_STORECHECK             272
#define IDS_SHIFTCASH                   272
#define IDS_LOGMSGLISTGHEADER           273
#define IDS_SHORTMSGRESULT              274
#define IDV_SHORTMSG                    275
#define IDS_SHORTMSGQUERY               275
#define IDD_RN_CARDDEREGISTER           276
#define IDS_NONAGEERROR                 276
#define IDS_CARDSTATE                   277
#define IDV_CARDOPENCONSUME             277
#define IDS_NEEDRETURNED                278
#define IDD_SET_CREDIT                  278
#define IDS_OPERATIONSUCCESS            279
#define IDD_SET_ONOFFDUTY               279
#define IDD_SET_DUTY                    279
#define IDS_CHECKOUTUSER                280
#define IDS_YJSB                        280
#define IDS_ERRORYJSB                   280
#define IDS_CREDITBEFOREBT              281
#define IDS_NOCONSUME                   282
#define IDS_CARDOPENCONSUME             283
#define IDS_CARDOPENCONSUMEHEAD         284
#define IDR_MENU_MUTIPAYOUT             284
#define IDS_TMPUSERCREDITLOG            285
#define IDS_NOENOUGHMONEY               286
#define IDS_REGDIPOSIT                  287
#define IDS_STRING288                   288
#define IDS_ONLINEBUNDTIME              288
#define IDS_PAYTYPE                     289
#define IDS_ONLINECHECKOUT              290
#define IDS_ONLINEQUERY                 291
#define IDS_MUTIPAYOUTHEAD              292
#define IDS_ONLINEBTFAILE               293
#define IDS_COMPUTERSTATUS              294
#define IDS_RETURNED                    295
#define IDS_RETURNLOG                   296
#define IDS_TTSERROR                    297
#define IDD_ND_MERGEMEMBER              298
#define IDS_PSWEMPTY                    298
#define IDS_CARDDEREGISTER              299
#define IDD_JXC_STORE                   299
#define IDS_INPUTEERRO                  300
#define IDD_JXC_COMMODITYSEL            301
#define IDS_NOMEMBERID                  301
#define IDD_DIALOG_ALLCHECKOUT          302
#define IDS_INPUTEMPTY                  302
#define IDD_DIALOG_SELTERMID            303
#define IDS_CHANGECOMPUTERERROR         303
#define IDS_CHANGECOMPUTERSUCCESS       304
#define IDD_JXC_RETAILONLINE            304
#define IDS_SELFDEFINEBUNDLETIME        305
#define IDS_NEEDMOREMONEY               306
#define IDD_SET_MONITOR                 306
#define IDD_ND_BUNDTIME_SELFDEFINE      307
#define IDS_ACTIVEMEMBERVIEW            307
#define IDS_CLIENTSET                   308
#define IDD_DIALOG_RETURN               309
#define IDS_PAYOUT2                     309
#define IDS_HASCHECKOUT                 309
#define IDR_ACTIVEMEMBER_MENU           310
#define IDS_ISERVERLOWVER               310
#define IDS_ONDUTY                      311
#define IDD_CONFIGCLIENT_BUNDLETIME     312
#define IDS_PLEASEONDUTYFISRT           312
#define IDS_PAYOUTMEMBER                313
#define IDD_CLIENTCONFIG_UNLOCK         314
#define IDS_OFFDUTYQUESTION             314
#define IDD_ND_BUNDLETIME2              315
#define IDS_ACTIVEMEMBERLISTHEAD        315
#define IDB_BITMAP1                     316
#define IDB_NETBARUSER                  316
#define IDS_ASKBUNDLETIMEAGEIN          316
#define IDD_ND_CREDIT                   317
#define IDS_INPUTBTMONEY                317
#define IDS_TERMTAKEUP                  318
#define IDD_ND_DREG                     319
#define IDS_RETURN2INFO                 319
#define IDS_RETURN2QUESTION             320
#define IDR_PNG_ENMERGENCY              321
#define IDS_BTCREDITREVERSEERROR        321
#define IDS_DETAILBALANCE               321
#define IDD_ND_CHECKINDLG               322
#define IDS_BTMONEYNOENOUGH             322
#define IDS_NOPRESENTCREDITASK          322
#define IDS_BTNEEDMONEY                 323
#define IDD_UNLOCKSCREENDLG             324
#define IDS_CLIENTCONNECTERROR          324
#define IDS_CREDITMODIFYOK              324
#define IDR_LASTUSERBACK                325
#define IDS_ACCOUNT_KIND                325
#define IDS_NOMONEYLOCK                 325
#define IDI_ICON1                       326
#define IDR_UDO                         326
#define IDS_CREDIT_KIND                 326
#define IDS_STRING326                   326
#define IDR_MSG_MENU                    327
#define IDS_BIRTHDAY                    327
#define IDD_ND_CREDITDIRECT             328
#define IDS_GUAJIERROR                  328
#define IDD_ND_BUNDTIME_SELFDEFINE1     329
#define IDD_ND_DEFINEBUNDTIME           329
#define IDS_DUTY_REMARK                 329
#define IDD_DLG_IBA_FAST                330
#define IDS_DUTY_REMARK2                330
#define IDR_FASTDLG                     331
#define IDS_MODIFYCREDIT                331
#define IDS_MODIFYMONEY                 332
#define IDS_DELETEMONEY                 333
#define IDS_OPENLOCAL                   334
#define IDS_CLOSELOCAL                  335
#define IDS_LOCALUSER                   336
#define IDS_DISABLEBT                   337
#define IDS_ZENGSHOUBAO                 338
#define IDB_BUGLE2                      338
#define IDB_BUGLE1                      339
#define IDS_CREDITERRORLOCAL            339
#define IDD_DLG_INPUT_PARAM             340
#define IDS_OPENLOCALUSER               340
#define IDD_DLG_CREDIT_MODIFY           341
#define IDS_FORBID_CREDIT               341
#define IDD_DIALOG_BOSSPWD_EX           342
#define IDS_FORBID_BUNDTIME             342
#define IDS_LOCALOPEN                   343
#define IDS_LOCALOFFDUTYERROR           344
#define IDD_DUTY_LOCAL                  344
#define IDS_FORBID_REVERSE              345
#define IDS_FORBID_LOCAL_REVERSE        346
#define IDR_PNG_STATE                   346
#define IDS_FORBID_CHECKIN              347
#define IDD_SET_PRINT                   347
#define IDS_FORBID_SOLD                 348
#define IDS_FORBID_LOCAL_SOLD           349
#define IDD_DIALOG1                     349
#define IDD_DIALOG_NOTICE               349
#define IDS_LOCALMODE_INFO              350
#define IDD_ND_ROOM                     350
#define IDS_LOCALUSER_RETURN            351
#define IDD_DLG_INPUT_MOBILE            351
#define IDS_AUTO_RETURN                 352
#define IDD_DIALOG2                     352
#define IDD_DLG_USER_PHOTO              352
#define IDS_ZSB_GUANGBO                 353
#define IDR_MENU2                       353
#define IDR_MENU_CHECKOUT               353
#define IDS_BJTD                        354
#define IDD_DIALOG3                     354
#define IDD_DLG_CAPPHOTO                354
#define IDS_BJTD_1                      355
#define IDS_BJTD_2                      356
#define IDD_DLG_REALNAME_ZDcrc          356
#define IDD_DLG_REALNAME_ZD1crc         356
#define IDS_BJTD_3                      357
#define IDD_DIALOG4                     357
#define IDD_DIALOG_CAPTURE              357
#define IDS_BJTD_4                      358
#define IDD_SET_CLEARDATA               358
#define IDS_BJTD_5                      359
#define IDD_DIALOG5                     359
#define IDS_BJTD_6                      360
#define IDS_BJTD_7                      361
#define IDS_CONSUME_LIST_HEAD           362
#define IDS_ZSB_GOOD                    363
#define IDS_CHECKIN_HEAD                364
#define IDS_SHORTMSG_HEAD               365
#define IDS_JXC_STORE_HEAD              366
#define IDS_JXC_STORE_HEAD2             367
#define IDS_JXC_COMM_HEAD1              368
#define IDS_JXC_COMM_HEAD2              369
#define IDS_JXC_COMM_SEL_HEAD           370
#define IDS_JXC_EXCHANGE_HEAD           371
#define IDS_JXC_PRESENT_HEAD            372
#define IDS_JXC_ONLINE_HEAD             373
#define IDS_JXC_RETURN_HEAD             374
#define IDS_JXC_SELL_HEAD               375
#define IDS_JXC_STORE_IN_HEAD           376
#define IDS_JXC_VOUCHER_HEAD            377
#define IDS_I_WANT_GO                   378
#define IDS_RETURN_F3                   379
#define IDS_BUNDLETIME_EX               380
#define IDS_USERNAME                    381
#define IDS_PC_NAME                     382
#define IDS_BALANCE                     383
#define IDS_CANCEL_ACTIVE               384
#define IDS_QUERY_CONSUME_LIST          385
#define IDS_ZSB_CONSUME_LIST            386
#define IDS_NO_PRESENT_CREDIT           387
#define IDS_DETAIL_EX                   388
#define IDS_REAL_TAKEIN                 389
#define IDS_CREDIT_C                    390
#define IDS_CREDIT                      391
#define IDS_CREDIT_F3                   392
#define IDS_RETURN_BUNDLETIME           393
#define IDS_OPEN_NETBAR                 394
#define IDS_BUNDLETIME_INFO             395
#define IDS_REAL_RETURN                 396
#define IDS_JZ_RETURN                   397
#define IDS_VIP_RETURN                  398
#define IDS_RETURN_FAILURE              399
#define IDS_JZ_FAILURE                  400
#define IDS_MAIN_MENU_CAPTION           401
#define IDS_WINDOW_LAYOUT               402
#define IDS_CHANGE_SKIN                 403
#define IDS_SITE_OPERATION              404
#define IDS_TASK_INFO                   405
#define IDS_REMOTE_OPERATION            406
#define IDS_JZ_RETURN_0                 407
#define IDCS_OK                         408
#define IDCS_CANCEL                     409
#define IDCS_YES                        410
#define IDCS_NO                         411
#define IDS_NETWORK_RESTORE             412
#define IDS_TRYING_CONNECTION           413
#define IDS_LOCALMODE                   414
#define IDS_USER_QUERY                  415
#define IDS_NETID                       416
#define IDS_QUERY_EX                    417
#define IDS_USERCLASS                   418
#define IDS_IDNUMBER                    419
#define IDS_LOOKUP_BALANCE              420
#define IDS_ACCOUNT_TOTAL               421
#define IDS_SHOULD_TAKEIN               422
#define IDS_BT_NO                       423
#define IDS_BT_MONEY                    424
#define IDS_BT_TYPE                     425
#define IDS_BT_AREA                     426
#define IDS_BT_REAL_MONEY               427
#define IDS_START_TIME                  428
#define IDS_END_TIME                    429
#define IDS_PRINT_TICKET                430
#define IDS_PRINT                       431
#define IDS_BUNDLETIME                  432
#define IDS_FORWARD_BT                  433
#define IDS_CHANGE_BT                   434
#define IDS_CANCEL_BT                   435
#define IDS_SELF_BT                     436
#define IDS_CASHIER_BT                  437
#define IDS_CREDIT_MODIFY               438
#define IDS_REFRESH                     439
#define IDS_AUTO_POWER_ON               440
#define IDS_CHECKIN                     441
#define IDS_MSGDLG_TIP                  442
#define IDS_SEND_RANGE                  443
#define IDS_CLOSE_C                     444
#define IDS_SEND_S                      445
#define IDS_SEND_MSG                    446
#define IDS_MODIFY_REMARK               447
#define IDS_REMARK                      448
#define IDS_CASHER_ON_FMT               449
#define IDS_CASHER_OFF_FMT              450
#define IDS_IBA_STATUS_TEXT             451
#define IDS_DIANKA_SELL                 452
#define IDS_ON_DUTY_INFO                453
#define IDS_DUTY_TYPE                   454
#define IDS_THIS_BEIYONGJIN             455
#define IDS_THIS_OTHER_INFO             456
#define IDS_CZK_MONEY                   457
#define IDS_ACCOUNT_SHOPPINT            458
#define IDS_ZSB_INFO                    459
#define IDS_ZSB_CONSUME                 460
#define IDS_ZSB_BALANCE                 461
#define IDS_CREDIT_MONEY                462
#define IDS_RETURN_MONEY                463
#define IDS_MONEY_SHOPPINT              464
#define IDS_CAIGOU_OUT                  465
#define IDS_OTHER_OUT                   466
#define IDS_DEPOSITE                    467
#define IDS_DUTY_INCOME                 468
#define IDS_PRE_KEEP                    469
#define IDS_CASH_TOTAL                  470
#define IDS_NEXT_KEEP                   471
#define IDS_HANDIN_AMOUNT               472
#define IDS_PANDIANKUCUN                473
#define IDS_STAT_DATA                   474
#define IDS_PRINT_GOODS                 475
#define IDS_PRINT_DUTY_REPORT           476
#define IDS_I_WANT_OFF                  477
#define IDS_THIS_DUTY_INFO              478
#define IDS_OPEN_USER                   479
#define IDS_OPEN_USER_EX                480
#define IDS_OPEN_TEMPUSER               481
#define IDS_OPEN_MEMBER                 482
#define IDS_IDTYPE                      483
#define IDS_SELECT_PC                   484
#define IDS_OPEN_BT                     485
#define IDS_SEX                         486
#define IDS_SCAN_ID                     487
#define IDS_AUTO_MAKE_NETID             488
#define IDS_SELECT_BT                   489
#define IDS_SELF_BT_2                   490
#define IDS_USERHASCARD                 491
#define IDS_RE_PRINT                    492
#define IDS_MODIFY_PWD                  493
#define IDS_MODIFY_PWD_EX               494
#define IDS_USER_ID                     495
#define IDS_PWD_LIMIT                   496
#define IDS_PRESENT_CREDIT0             497
#define IDS_PRESENT_ACCOUNT             498
#define IDS_POINT2                      499
#define IDS_PRESENT_CREDIT1             500
#define IDS_CREDIT_CARD_INFO            501
#define IDS_CARD_NO                     502
#define IDS_PASSWORD                    503
#define IDS_KIND                        504
#define IDS_MONEY                       505
#define IDS_READ_CREDIT_CARD            506
#define IDS_CARD_CREDIT                 507
#define IDS_VISUAL_CARD                 508
#define IDS_REAL_CARD                   509
#define IDS_REAL_CARD2                  510
#define IDS_NO_PRESENT_ACCOUNT          511
#define IDS_HAS_PRESENT_ACCOUNT         512
#define IDS_PRE_RESERVE                 513
#define IDS_BT_LEAVE_TIME               514
#define IDS_BT_SEGMENT                  515
#define IDS_ACCOUNT_INFO                516
#define IDS_CREDIT_AND_PRINT            517
#define IDS_RETURN_EX                   518
#define IDS_REMOTE_CHECKOUT             519
#define IDS_CAN_RETURN_MONEY            520
#define IDS_CREDIT_RETURN               521
#define IDS_COMSUME_LIST                522
#define IDS_LOCAL_CREDIT_FAULT          523
#define IDS_IBA_NET_STATUS              524
#define IDS_JXC_TABS                    525
#define IDS_PAYTYPE_COMBO               526
#define IDS_PAYTYPE_COMBO_EX            527
#define IDS_QUERY_JXC_TYPE              528
#define IDS_OPT_TYPE_NAMES              529
#define IDS_OPTYPE_BALANCE              530
#define IDS_OPTYPE_BALANCE_EX           531
#define IDS_OP_VIEW_OPEN_HEAD           532
#define IDS_OP_VIEW_CREDIT_HEAD         533
#define IDS_OP_VIEW_RETURN_HEAD         534
#define IDS_OP_VIEW_REVERSE_HEAD        535
#define IDS_OP_VIEW_CARD_HEAD           536
#define IDS_OP_VIEW_UP_HEAD             537
#define IDS_ALL                         538
#define IDS_OP_VIEW_TYPES               539
#define IDS_COM_LIST_TYPES              540
#define IDS_OP_VIEW_RESULT              541
#define IDS_RZX_NAME_IP                 542
#define IDS_GLV_NAME_IP                 543
#define IDS_WD_NAME_IP                  544
#define IDS_DUTY_NEXTRESERVE_ERROR      545
#define IDS_BALANCE_REMINDER            546
#define IDS_NOTICE_BTN_NAMES            547
#define IDS_ENSURE_REBILLING            548
#define IDS_CHECKOUT_RECORD             549
#define IDS_CHECKOUT_RECORD_HEAD        550
#define IDS_REFUND_RECORD_HEAD          551
#define IDS_OPERATION_AFTER             552
#define IDS_ROOM_LIST_HEAD              553
#define IDS_ROOM_IDLE                   554
#define IDS_ROOM_STANDALONE             555
#define IDS_ROOM_WHOLE                  556
#define IDS_ROOM_OPEN                   557
#define IDS_ROOM_RETURN                 558
#define IDS_ROOM_BODY                   559
#define IDS_ROOM_CHECKOUT               560
#define IDS_ROOM_REFUND                 561
#define IDS_ROOM_OPENED                 562
#define IDS_ROOM_OPEN_TIME              563
#define IDS_ROOM_CHECKIN_ERROR1         564
#define IDS_PRESENT_FORMAT              565
#define IDS_DEPOSIT_FORMAT              566
#define IDS_PASSWORD_FORMAT             567
#define IDS_BUNDLETIME_FORMAT           568
#define IDS_ROOM_HAS_REFUND             569
#define IDS_OVERFLOW_MAXMONEY           570
#define IDS_STRING571                   571
#define IDS_OVERFLOW_MAXMONEY2          571
#define IDS_IBA_RESTART_TIP             572
#define IDS_IBA_VERBELOW_TIP            573
#define IDS_INVALID_MOBILE              574
#define IDS_NETBAR_NOTICE               575
#define IDS_NETBAR_NOTICE_TIPS          576
#define IDS_ERROR_TELNUM_TIPS           577
#define IDS_ERROR_TELNUM_COUNT          578
#define IDS_ERROR_TELNUM_EMPTY          579
#define IDS_ERROR_TELNUM_ALERADY_BIND   580
#define IDS_SCAN2_BACK_SUCCESS          581
#define IDS_SCAN2_BACK_FAILED           582
#define IDS_ERROR_PHOTO                 583
#define IDS_VEDIO_OVERWRITE             584
#define IDS_VEDIO_TIMEOUT               585
#define IDS_VEDIO_DELETEFAILED          586
#define IDS_VEDIO_CAPTURE_FAILED        587
#define IDS_VEDIO_NO_DEVICE             588
#define IDS_READCARD_FAILED             589
#define IDS_NOTERMTOADD                 590
#define IDS_CLEAR_SHORTMSG_SUCCESSED    591
#define IDS_CLEAR_SHORTMSG_FAILED       592
#define IDS_STRING592                   592
#define IDC_STATIC_USERNAME             1031
#define IDC_STATIC_MEMBERID             1032
#define IDC_STATIC_USERNAME2            1033
#define IDC_STATIC_MEMBERID2            1034
#define IDC_STATIC_CREDITCARD           1035
#define IDC_STATIC_NETBARPAY            1036
#define IDC_STATIC_STOREIN              1037
#define IDC_STATIC_WXAMOUNT             1038
#define IDC_STATIC_ZSB_CONSUME          1040
#define IDC_BUTTON_FORWARDBT            1041
#define IDC_STATIC_ZSB_BALANCE          1041
#define IDC_BUTTON1                     1042
#define IDC_BUTTON_BROWSER              1042
#define IDC_BUTTON_MUTIREFUND           1042
#define IDC_BUTTON_BUNDTIME             1042
#define IDC_BUTTON_STORECHECK           1042
#define IDC_BUTTON_PRINTCOMMODITY       1042
#define IDC_BUTTON_SYNCSERVER           1042
#define IDC_BUTTON_CHECKOUTTOSERVER     1042
#define IDC_SELFBUNDTIME                1042
#define IDC_BUTTON_ALLCHECKOUT          1042
#define IDC_BUTTON_DODONEW              1042
#define IDC_BUTTON_ENMERGENCY           1042
#define IDC_BUTTON_REFRESH              1042
#define IDC_BUTTON_PREV                 1042
#define IDC_BUTTON_EMAIL                1042
#define IDC_BTN_CUSTOM_BOUNDLETIME      1042
#define IDC_BTN_QUERY                   1042
#define IDC_EDIT_USERNAME               1043
#define IDC_EDIT_USERID                 1044
#define IDC_BUTTON2                     1045
#define IDC_BUTTON_CANCELACTIVE         1045
#define IDC_BUTTON_MUTIPAYOUT           1045
#define IDC_BUTTON_SUNLIKE              1045
#define IDC_BUTTON_NEXT                 1045
#define IDC_BUTTON_BBS                  1045
#define IDC_BUTTON_BALANCE              1045
#define IDC_BUTTON_LOCAL                1045
#define IDC_BTN_CREDIT                  1045
#define IDC_BTN_INPUT_NUMBER            1045
#define IDC_BTNCAPPHOTO                 1045
#define IDC_BTN_CAPPHOTO                1045
#define IDC_BTN_CLAEAN_SHORTMSG         1045
#define IDC_BUTTON3                     1046
#define IDC_BUTTON_CREDITPRINT          1046
#define IDC_BUTTON_DUDUNIU              1046
#define IDC_BUTTON_ONLINE               1046
#define IDC_BTNCHOOSECAMERA             1046
#define IDC_BTN_CHOOSECAMERA            1046
#define IDC_BUTTON4                     1047
#define IDC_COMBO_CASHIER               1047
#define IDC_EDIT_PASSWORD               1048
#define IDC_EDIT_PWD                    1048
#define IDC_EDIT_SHORTMSG               1049
#define IDC_EDIT_PWD2                   1049
#define IDC_COMBO_PCCLASS               1050
#define IDC_SENDSHORMSG                 1052
#define IDC_CLOSE                       1053
#define IDC_STATIC_IE                   1054
#define IDC_EDIT_RESERVE                1056
#define IDC_COMBO_SEX                   1058
#define IDC_EDIT_PERSONALID             1059
#define IDC_EDIT_TELNUM                 1060
#define IDC_COMBO_IDTYPE                1061
#define IDC_EDIT_MONEY                  1062
#define IDC_COMBO_USERCLASS             1063
#define IDC_CHECK_USERHASCARD           1064
#define IDC_CHECK_PRESENT               1065
#define IDC_BUTTON_QUERY                1067
#define IDC_BUTTON_READID2              1068
#define IDC_CHECK_TEMP                  1069
#define IDC_BTN_RN_REG                  1069
#define IDC_CHECK_PRINT                 1070
#define IDC_BTN_RN_REG2                 1070
#define IDC_EDIT_COSTEXPENSE            1071
#define IDC_BUTTON_QUERY_TEL            1071
#define IDC_EDIT_DEPOSIT                1072
#define IDC_BUTTON_QUERY2               1072
#define IDC_BTN_PHOTO                   1072
#define IDC_STATIC_RESULT               1073
#define IDC_EDIT_NETBAR                 1075
#define IDC_EDIT_NAME                   1076
#define IDC_EDIT_ZSZH                   1077
#define IDC_EDIT_YSCZ                   1078
#define IDC_EDIT_CLASS                  1080
#define IDC_EDIT_ALL                    1081
#define IDC_EDIT_WSCZ                   1082
#define IDC_EDIT_MEMBERID               1084
#define IDC_EDIT_ZHYE                   1085
#define IDC_EDIT_CREDIT                 1086
#define IDC_EDIT_ZTJE                   1087
#define IDC_BUTTON_REFUNDMENT           1089
#define IDC_BUTTON5                     1091
#define IDC_BUTTON_READCARD             1092
#define IDC_EDIT_ID                     1093
#define IDC_EDIT_IDCARDSNO              1094
#define IDC_EDIT_TERMID                 1095
#define IDC_EDIT_IDCARDSNO2             1095
#define IDC_EDIT_COMPUTER               1096
#define IDC_EDIT_CASHPAY                1099
#define IDC_EDIT_CREDITCARD             1100
#define IDC_EDIT_RETURNED               1101
#define IDC_EDIT_PAYOUT                 1102
#define IDC_EDIT_NEXTRESERVE            1103
#define IDC_BUTTON_STAT                 1104
#define IDC_STATIC_VER                  1105
#define IDC_LIST_CREDIT                 1107
#define IDC_EDIT_CREDITTIME             1108
#define IDC_EDIT_BTMONEY2               1115
#define IDC_CHECK_SHOWALL               1116
#define IDC_CHECK_POPMSGBOX             1117
#define IDC_BUTTON_CLONLINE             1118
#define IDC_BUTTON_CLVIP                1119
#define IDC_BUTTON_CLLM                 1120
#define IDC_BUTTON_CLOFFLINE            1121
#define IDC_BUTTON_CLLOCK               1122
#define IDC_BUTTON_CLBD                 1123
#define IDC_BUTTON_CLBLACK              1124
#define IDC_BUTTON_CLSUSPEND            1125
#define IDC_BUTTON_CLTHIEF              1126
#define IDC_BUTTON_CLUNLOCK             1127
#define IDC_EDIT_OLDPWD                 1128
#define IDC_EDIT_NEWPWD                 1129
#define IDC_EDIT_CONPWD                 1130
#define IDC_BUTTON_MODIFY               1133
#define IDC_LIST_BUNDLETIME             1134
#define IDC_EDIT_BTSTARTTIME            1136
#define IDC_EDIT_BTID                   1137
#define IDC_EDIT_BTENDTIME              1138
#define IDC_EDIT_BTMONEY                1139
#define IDC_EDIT_BTAREA                 1140
#define IDC_EDIT_BTYPE                  1141
#define IDC_BUTTON_CANCELBT             1142
#define IDC_BUTTON_CHANGEBT             1143
#define IDC_BUTTON_CHANGEUSERSN         1144
#define IDC_CHECK_OPEN                  1145
#define IDC_CHECK_AUTOSORT              1146
#define IDC_CHECK_ENMERGENCY            1146
#define IDC_CHECK_PAUSEREVMSG           1147
#define IDC_EDIT_MINIMONEY              1148
#define IDC_COMBO_PASSWORDTYPE          1149
#define IDC_COMBO_PASSWORDTYPE2         1150
#define IDC_COMBO_FONTSIZE              1153
#define IDC_CHECK_LOCALMODE             1155
#define IDC_COMBO_AFFTERCHECKOUT        1157
#define IDC_EDIT_SHUTDOWNTIME           1159
#define IDC_EDIT_NETBARKEY              1164
#define IDC_EDIT_CENTERIP               1165
#define IDC_EDIT_CENTERPORT             1166
#define IDC_BUTTON_SYNC                 1167
#define IDC_EDIT_NETBARID               1170
#define IDC_EDIT_ADDR                   1171
#define IDC_EDIT_TEL                    1172
#define IDC_EDIT_REAL                   1173
#define IDC_EDIT_PROXYIP                1174
#define IDC_EDIT_WWMIP                  1176
#define IDC_EDIT_PATH                   1177
#define IDC_BUTTON_SET                  1178
#define IDC_CHECK_UNLOCKSUSPEND         1179
#define IDC_CHECK_BUNDLETIME            1179
#define IDC_LIST_CONFIG                 1180
#define IDC_BUTTON_SCANRECO             1181
#define IDC_BUTTON_RECENTCREDIT         1182
#define IDC_BUTTON_CHECKOUT             1183
#define IDC_BUTTON_BUNDLETIME           1184
#define IDC_EDIT_BDINFO                 1185
#define IDC_EDIT_NATION                 1187
#define IDC_EDIT_OFFICER                1188
#define IDC_STATIC_TEL                  1189
#define IDC_STATIC_NATION               1190
#define IDC_STATIC_OFFICER              1191
#define IDC_LIST_CONSUMELIST            1192
#define IDC_BUTTON_CONSUMELIST          1193
#define IDC_COMBO_CONSUMETYPE           1194
#define IDC_BUTTON_CONSUMELIST2         1194
#define IDC_BUTTON_DETAIL               1195
#define IDC_BUTTON_STARTTIME            1196
#define IDC_BUTTON_ENDTIME              1197
#define IDC_COMBO_TERMID                1198
#define IDC_COMBO_SHIFT                 1199
#define IDC_BUTTON_PRINT                1200
#define IDC_EDIT_ONDUTYTIME             1201
#define IDC_EDIT_OFFDUTYTIME            1202
#define IDC_EDIT_MEMO                   1203
#define IDC_EDIT_REESON                 1204
#define IDC_BUTTON_UPGRADE              1205
#define IDC_BUTTON_CREDIT               1206
#define IDC_BUTTON_RETURN2              1207
#define IDC_LIST_COMMON                 1211
#define IDC_COMBO_OPERATION             1212
#define IDC_TREE_POPEDOM                1213
#define IDC_STATIC_PERSONALID           1214
#define IDC_BUTTON_GETPOPEDOM           1215
#define IDC_STATIC_PERSONALID2          1215
#define IDC_EDIT_CASHREGISTERID         1216
#define IDC_STATIC_NETBAR               1217
#define IDC_STATIC_ALL                  1218
#define IDC_STATIC_POINT                1219
#define IDC_STATIC_NETBARID             1220
#define IDC_STATIC_NETBAR2              1220
#define IDC_STATIC_ALL2                 1221
#define IDC_STATIC_CLASS                1223
#define IDC_STATIC_YSCZ                 1224
#define IDC_STATIC_WSCZ                 1225
#define IDC_STATIC_ZSZH                 1226
#define IDC_STATIC_YSCZ2                1227
#define IDC_STATIC_REFNO                1228
#define IDC_STATIC_WSCZ2                1228
#define IDC_STATIC_ZSZH2                1229
#define IDC_STATIC_ONDUTYTIME           1230
#define IDC_STATIC_CLASS2               1230
#define IDC_STATIC_RESERVE              1231
#define IDC_STATIC_DEPOSIT              1232
#define IDC_STATIC_COSTEXPENSE          1233
#define IDC_STATIC_CREDIT               1234
#define IDC_STATIC_CREDITTIME           1235
#define IDC_STATIC_RETURNED             1236
#define IDC_STATIC_CASHPAY              1237
#define IDC_CHECK_REAALNAME             1239
#define IDC_COMBO_SCAN                  1240
#define IDC_EDIT_ISERVERIP              1241
#define IDC_EDIT_CONFIG1                1243
#define IDC_EDIT_CONFIG2                1244
#define IDC_EDIT_CONFIG3                1245
#define IDC_BUTTON_SAVE                 1246
#define IDC_STATIC_ZTJE                 1248
#define IDC_EDIT_MAC                    1251
#define IDC_STATIC1                     1252
#define IDC_STATIC2                     1253
#define IDC_STATIC3                     1254
#define IDC_STATIC_NAME                 1255
#define IDC_STATIC_ADDR                 1256
#define IDC_STATIC5                     1256
#define IDC_COMBO_SHIFTREPORTTYPE       1258
#define IDC_STATIC_INFO                 1259
#define IDC_LIST_COMMODITY              1260
#define IDC_EDIT_COMMODITYID            1261
#define IDC_EDIT_COMMODITYTD            1262
#define IDC_STATIC_TYPE                 1263
#define IDC_STATIC_PRICE                1264
#define IDC_BUTTON_COMMODITY            1265
#define IDC_EDIT_COUNT                  1267
#define IDC_BUTTON_ADD                  1268
#define IDC_BUTTON_DEL                  1269
#define IDC_BUTTON_CLEAR                1270
#define IDC_EDIT_NETID                  1273
#define IDC_COMBO_PAYTYPE               1275
#define IDC_STATIC_COMMODITYID          1276
#define IDC_STATIC_MONEY                1277
#define IDC_EDIT_VOUCHERNO              1278
#define IDC_BUTTON_VOUCHERNO            1279
#define IDC_COMBO_WAY                   1281
#define IDC_STATIC_NETCASH              1282
#define IDC_STATIC_JXC                  1283
#define IDC_BUTTON_JXCPRINT             1284
#define IDC_STATIC_STORE                1285
#define IDC_COMBO_STORE                 1286
#define IDC_CHECK_TTS                   1287
#define IDC_COMBO_TTS                   1288
#define IDC_SLIDER_SOUND                1289
#define IDC_BUTTON_TTS                  1291
#define IDC_STATIC_IDIMAGE              1293
#define IDC_STATIC_PERSONGIMAGE         1294
#define IDC_STATIC_BUNDLETIME           1295
#define IDC_STATIC_BTMONEY              1296
#define IDC_STATIC_BTSTARTTIME          1297
#define IDC_STATIC_BTID                 1298
#define IDC_STATIC_BTMONEY2             1299
#define IDC_LIST_INFO                   1300
#define IDC_LIST_MEMBERINFO             1300
#define IDC_STATIC_BTYPE                1301
#define IDC_STATIC_BTAREA               1302
#define IDC_STATIC_BTENDTIME            1303
#define IDC_CHECK_TEMPMEMBER            1304
#define IDC_BUTTON_CONSUME              1305
#define IDC_COMBO_USERTYPE              1306
#define IDC_COMBO_TERMINALID            1306
#define IDC_COMBO_BTSEL                 1306
#define IDC_COMBO_SORT                  1306
#define IDC_COMBO_REGISTERAGE           1306
#define IDC_COMBO_RETURNACTION          1306
#define IDC_BUTTON_CLUSERTYPE           1307
#define IDC_CHECK_REFUNDMENT            1308
#define IDC_EDIT_REFUNDTIME             1309
#define IDC_STATIC_REFUNDTIME           1310
#define IDC_BUTTON_REPRINT              1311
#define IDC_STATIC_HANDLEIN             1314
#define IDC_CHECK_DYNAMICREVERSE        1315
#define IDC_STATIC2_HANDLEIN            1316
#define IDC_STATIC2_NEXTRESERVE         1318
#define IDC_EDIT_NEXTREVERSE            1319
#define IDC_STATIC_RNCARDID             1320
#define IDC_STATIC_RNNAME               1321
#define IDC_STATIC_RNCLASSNAME          1322
#define IDC_STATIC_RNCERTIFICATECLASS   1323
#define IDC_STATIC_RNCERTIFICATEID      1324
#define IDC_STATIC_MSG                  1325
#define IDC_STATIC_RNUSERCLASS          1326
#define IDC_STATIC_SLCARDID             1327
#define IDC_STATIC_SLCLASSNAME          1328
#define IDC_STATIC_SLNAME               1328
#define IDC_STATIC_SLUSERCLASS          1329
#define IDC_STATIC_SLCERTIFICATECLASS   1330
#define IDC_STATIC_SLCERTIFICATEID      1331
#define IDC_EDIT_PRESENTNAME            1334
#define IDC_EDIT_EXCHANGEPOINT          1338
#define IDC_STATIC_AGENTNAME            1339
#define IDC_STATIC_REGULARTEL           1340
#define IDC_STATIC_MOBILEPHONE          1341
#define IDC_EDIT_MAXKEEPTIME            1341
#define IDC_EDIT_MAXKEEPTIMEOFUKEY      1342
#define IDC_EDIT_INSTALLPWD             1343
#define IDC_EDIT_SETUPPWD               1343
#define IDC_STATIC0                     1344
#define IDC_STATIC4                     1345
#define IDC_EDIT_BIYMAPPATH             1354
#define IDC_COMBO_TREMINALIP            1355
#define IDC_CHECK_PRINTSHIFT            1376
#define IDC_STATIC_TIP                  1377
#define IDC_STATIC_BUNDTIMETYPE         1380
#define IDC_STATIC_BTREMAINTIME         1380
#define IDC_STATIC_BUNDTINELIMIT        1381
#define IDC_STATIC_BUNDTIMEMONEY        1382
#define IDC_STATIC_COMMODITY            1386
#define IDC_LIST_MSG                    1388
#define IDC_CHECK_CREDITPREBT           1390
#define IDC_EDIT_REGISTERMONEY          1392
#define IDC_CHECK_TMPCHANGECOMPUTER     1394
#define IDC_CHECK_MEMBERCHANGECOMPUTER  1395
#define IDC_CHECK_FETCHAMOUNT           1396
#define IDC_STATIC_SHIFTCASH            1397
#define IDC_CHECK_NOTSHOW_DUTYBTN       1397
#define IDC_CHECK_SHOWRETURNMONEY       1398
#define IDC_STATICZTJE                  1399
#define IDC_LIST_USERINFO               1401
#define IDC_CHECK_SHOWUSETIME           1402
#define IDC_BUTTON_BUNDTIMECOLOR        1403
#define IDC_COMBO_PRINTTYPE             1406
#define IDC_RICHEDIT_PRINTFINFO         1407
#define IDC_CHECK_ALLOWBUNDTIME         1408
#define IDC_CHECK_ALLOWSUSPEND          1409
#define IDC_STATIC_UINT                 1411
#define IDC_EDIT_PRICE                  1412
#define IDC_STATIC_TOTALAMOUNT          1414
#define IDC_CHECK_EDITPAYOUT            1415
#define IDC_EDIT_COUNT2                 1417
#define IDC_STATIC_UINT2                1418
#define IDC_STATIC_PRICEUNIT            1419
#define IDC_STATIC_UNITMUTIPLE          1420
#define IDC_CHECK_HASCARD               1421
#define IDC_EDIT_FIND                   1425
#define IDC_STATIC_ONLINEAMOUNT         1426
#define IDC_STATIC_CHECKOUT             1436
#define IDC_SHOWZONELIST                1437
#define IDC_EDIT_BUNDTIMEMONEY          1438
#define IDC_COMBO_ZONE                  1439
#define IDC_COMBO_ACCOUNTTYPE           1440
#define IDC_EDIT_HOUR                   1442
#define IDC_EDIT_MIN                    1443
#define IDC_STATIC_                     1444
#define IDC_STATIC_HELP                 1444
#define IDC_CHECK_TWOSHIFT              1445
#define IDC_EDIT_SHIFT1NAME             1446
#define IDC_EDIT_SHIFT2NAME             1448
#define IDC_EDIT_SHIFT3NAME             1450
#define IDC_COMBO_SHIFT1STARTTIME       1453
#define IDC_COMBO_SHIFT1ENDTIME         1454
#define IDC_CHECK1                      1454
#define IDC_CHECK_CHECKIDCARDNUMBER     1454
#define IDC_CHECK_OPENAFTERENTER        1454
#define IDC_CHECK_POWERON               1454
#define IDC_CHECK_LASTUSER              1454
#define IDC_CHECK_AUTO_START            1454
#define IDC_CHECK_PAY_TYPE              1454
#define IDC_CHECK_REMINDER              1454
#define IDC_CHECK_TICKET                1454
#define IDC_CHECK_MEM_OPEN              1454
#define IDC_COMBO_SHIFT2STARTTIME       1455
#define IDC_CHECK_MEM_CREDIT            1455
#define IDC_COMBO_SHIFT2ENDTIME         1456
#define IDC_CHECK_MEM_BT                1456
#define IDC_COMBO_SHIFTCOUNT            1457
#define IDC_CHECK_TEMP_OPEN             1457
#define IDC_COMBO_SHIFT3STARTTIME       1458
#define IDC_STATIC_NETID                1458
#define IDC_CHECK_TEMP_CREDIT           1458
#define IDC_COMBO_SHIFT3ENDTIME         1459
#define IDC_RADIO_TEMPUSER              1459
#define IDC_CHECK_TEMP_BT               1459
#define IDC_RADIO_MEMBER                1460
#define IDC_COMBO1                      1461
#define IDC_COMBO_TEMPUSERCLASS         1461
#define IDC_COMBO_TEMP                  1461
#define IDC_COMBO_OPERATIONAFTERSWIPINGCARD 1461
#define IDC_COMBO_ACCOUNT               1461
#define IDC_COMBO_FAST                  1461
#define IDC_COMBO_CAMERADEVICES         1461
#define IDC_COMBO_MEMBER                1462
#define IDC_COMBO_AFTER_ENTER           1462
#define IDC_EDIT_NOENOUGHTIME           1463
#define IDC_COMBO_AFTER_DCLICK          1463
#define IDC_COMBO_FONTTYPE              1464
#define IDC_STATIC_TERMID               1466
#define IDC_STATIC2_DEPOSIT             1470
#define IDC_STATIC_WWMIP                1471
#define IDC_GIRD_RECT                   1472
#define IDC_COMBO_COMPUTER              1474
#define IDC_COMBO_TEMPSORT              1475
#define IDC_CHECK_FEE                   1476
#define IDC_STATIC_CAPTION              1477
#define IDC_STATIC_CREDITMONEY          1478
#define IDC_EDIT1                       1479
#define IDC_EDIT_LASTLY_MSG             1479
#define IDC_EDIT_CREDITMONEY            1479
#define IDC_COMBO_KIND                  1480
#define IDC_EDIT2                       1480
#define IDC_STATIC_400TEL               1481
#define IDC_CHECK_MSG_RB                1482
#define IDC_CHECK3                      1483
#define IDC_CHECK_MSG_AUTOHIDE          1483
#define IDC_CHECK_MEM_RETURN            1483
#define IDC_PIC_BUGLE                   1484
#define IDC_STATIC_CONTENT              1485
#define IDC_STATIC_1                    1486
#define IDC_STATIC_2                    1487
#define IDC_STATIC_TXT                  1488
#define IDC_STATIC_27                   1488
#define IDC_CHECK_ALLOWNEXT             1489
#define IDC_STATIC_CURRENT              1490
#define IDC_STATIC_SELFDUTY             1491
#define IDC_STATIC_GROUP_TEXT           1492
#define IDC_EDIT_BT_LIMIT               1493
#define IDC_STATIC_BIRTHDAY             1494
#define IDC_CHECK_STARTLOCAL            1495
#define IDC_STATIC_GROUP                1496
#define IDC_STATIC_MODE                 1497
#define IDC_STATIC_LOCALTIP             1498
#define IDC_RADIO1                      1500
#define IDC_RADIO2                      1501
#define IDC_STATIC_OTHER                1501
#define IDC_RADIO3                      1502
#define IDC_STATIC_REMARK               1505
#define IDC_STATIC_3                    1506
#define IDC_STATIC_4                    1507
#define IDC_STATIC_5                    1508
#define IDC_STATIC_6                    1509
#define IDC_STATIC_7                    1510
#define IDC_STATIC_8                    1511
#define IDC_STATIC_9                    1512
#define IDC_STATIC_10                   1513
#define IDC_STATIC_11                   1514
#define IDC_STATIC_12                   1515
#define IDC_STATIC_13                   1516
#define IDC_STATIC_14                   1517
#define IDC_PIC_STATUS                  1518
#define IDC_STATIC_28                   1518
#define IDC_STATIC_WXTEXT               1518
#define IDC_STATIC_15                   1519
#define IDC_STATIC_DIANKA               1520
#define IDC_STATIC_16                   1521
#define IDC_STATIC_17                   1522
#define IDC_STATIC_18                   1523
#define IDC_STATIC_19                   1524
#define IDC_STATIC_20                   1525
#define IDC_STATIC_21                   1526
#define IDC_STATIC_22                   1527
#define IDC_STATIC_23                   1528
#define IDC_STATIC_24                   1529
#define IDC_STATIC_25                   1530
#define IDC_STATIC_26                   1531
#define IDC_LIST1                       1532
#define IDC_STATIC_BYJ_HIT              1533
#define IDC_CHECK_TEMP_RETURN           1534
#define IDC_CHECK_AUTO_RETURN           1535
#define IDC_CHECK_USER_CHECKIN          1536
#define IDC_STATIC_BUILD                1537
#define IDC_CHECK_FORBID_SCREEN         1537
#define IDC_EDIT_MAX_MONEY              1538
#define IDC_STATIC_PHOTO                1539
#define IDC_LIST_DEVICES                1540
#define IDC_STATIC_PIC                  1541
#define IDC_BTN_CAPPHTOTO               1542
#define IDC_BTN_JUBAO                   1542
#define IDC_STATIC_ZJIMG                1542
#define IDC_STATIC_ZCIMG                1543
#define IDC_EDIT_FIX_RESERVE            1544
#define IDC_EDIT_CRC                    1545
#define IDC_STATIC_VIDEO                1546
#define IDC_BTN_STARTTIME               1549
#define IDC_BTN_ENDTIME                 1550
#define IDM_MINCOLUMNCMD                32000
#define IDM_MAXCOLUMNCMD                32050
#define IDM_MINQUICKMSG                 32100
#define IDM_MAXQUICKMSG                 32200
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_CAPTIONBAR              32816
#define ID_VIEW_OUTLOOKBAR              32817
#define ID_SHORTCUTS_PANE_1             32824
#define ID_SHORTCUTS_PANE_2             32825
#define ID_SHORTCUTS_TREE               32826
#define ID_VIEW_APPLOOK_2000            32833
#define ID_VIEW_APPLOOK_XP              32834
#define ID_VIEW_APPLOOK_2003            32835
#define ID_VIEW_APPLOOK_WIN_XP          32836
#define ID_VIEW_APPLOOK_VS2005          32837
#define ID_VIEW_APPLOOK_2007_1          32838
#define ID_VIEW_APPLOOK_2007_2          32839
#define ID_VIEW_APPLOOK_2007_3          32840
#define ID_VIEW_APPLOOK_2007_4          32841
#define ID_VIEW_APPLOOK_VS2008          32842
#define ID_DUTY_ON                      32849
#define ID_DUTY_OFF                     32850
#define ID_FASTLANELABEL                32851
#define ID_FASTLANECOMBO                32852
#define ID_REFRESH                      32853
#define IDM_FASTLANE                    32856
#define IDM_SNAPSCREEN                  32858
#define IDM_GETLOG                      32859
#define IDM_RRMOTEOPERATION             32860
#define IDM_POWEROFF                    32861
#define IDM_POWERON                     32863
#define IDM_SENDSHORTMESSAGE            32865
#define IDM_SUNLIKEWEB                  32873
#define IDM_CALC                        32875
#define IDM_NOTEPAD                     32876
#define IDM_EDITSHORTMSG                32877
#define IDM_EDITQUICKMSG                32878
#define IDM_NEWUSER                     32880
#define IDM_CREDIT                      32882
#define IDM_DECAREDLOSS                 32885
#define IDM_LOSS                        32886
#define IDM_CANCELLOSS                  32890
#define IDM_CREDITONLINE                32892
#define ID_COLUMN                       32893
#define IDM_COLUMN_SET                  32896
#define IDM_CREDITREVERSE               32899
#define IDM_SWITHUSER                   32903
#define IDM_CASHSALE                    32909
#define IDM_MODIFYUSERINFO              32911
#define IDM_MODIFYPWS                   32913
#define IDM_IBASET                      32918
#define IDM_NETBARSET                   32919
#define IDM_ENTERBOSSMODE               32922
#define IDM_HANDBACK                    32923
#define IDM_MODIFYBOSSPWD               32926
#define IDM_PAYOUT                      32928
#define IDM_UNUSUAL                     32929
#define IDM_MODIFYPWD                   32930
#define IDM_BOUNDTIME                   32932
#define IDM_CHANGESN                    32934
#define IDM_REBOOT                      32937
#define IDM_CONSUMELIST                 32939
#define IDM_TERMCONSUME                 32940
#define IDM_UPGRADE                     32942
#define IDM_SCAN1                       32950
#define IDM_SCAN2                       32951
#define IDM_READ2                       32952
#define IDM_SHIFTCASH                   32954
#define IDM_OPERATION                   32956
#define IDM_CARDCREDIT                  32960
#define IDM_POPEDOM                     32968
#define IDM_RN_OPENCARD                 32973
#define IDM_RN_LOSE                     32974
#define IDM_RN_MODIFYPWD                32975
#define IDM_RN_ADDMEMBER                32976
#define IDM_RN_DEREG                    32977
#define IDM_LOGPATH                     32985
#define IDM_CONSUMELIST2                32990
#define IDM_TERMCONSUME2                32991
#define IDM_REALNAMESET                 32992
#define IDM_OTHERSET                    32994
#define IDM_CLIENTSET                   32995
#define IDM_SELL                        32997
#define ID_SCAN_OTHER                   33008
#define ID_POINTEXCHANGE                33010
#define IDM_POINTEXCHANGE               33012
#define ID_33015                        33015
#define IDM_AGENT                       33016
#define ID_MENU_FULLZOOM                33020
#define ID_MENU_SCROLLZOOM              33021
#define ID_33022                        33022
#define ID_33025                        33025
#define ID_Menu                         33026
#define ID_SEAT_ADDSEAT                 33027
#define ID_SEAT_LOCKSEAT                33028
#define ID_SEAT_SAVE                    33029
#define ID_SEAT_LOADSEAT                33030
#define ID_SEAT_SAVESEAT                33031
#define ID_Menu33032                    33032
#define IDM_SEAT_DEL                    33033
#define IDM_SEAT_REFRESH                33034
#define IDM_SEATOPERATION               33036
#define IDM_CLOCKWISE                   33038
#define IDM_MUTIREFUND                  33041
#define IDM_SERVERWEB                   33048
#define IDM_SHORTMSGQUERY               33050
#define IDM_ALLLOG                      33057
#define IDM_MUTIPAYOUT                  33058
#define IDM_POPUP_PAYOUT                33059
#define IDM_PRINTTEMPLATE               33060
#define IDM_BUNDTIMEONLINE              33066
#define IDM_MERGEMEMBER                 33067
#define IDM_MUTICHECKOUT                33068
#define ID_CONFORMRETURN                33074
#define ID_CANCELRETURN                 33075
#define IDM_SPEECHTEMPLATE              33078
#define IDM_BOUNDTIME2                  33089
#define IDM_CHANGECOMPUTER              33091
#define IDM_MYREFRESH                   33092
#define IDM_RETAILONLINE                33093
#define IDM_PING                        33094
#define IDM_CHECKIN                     33096
#define IDM_UNLOCKSCREEN                33098
#define ID_COPY_MSG                     33101
#define IDM_CREDITDIRECT                33103
#define ID_BUTTON33104                  33104
#define ID_BUTTON33105                  33105
#define ID_FASTLANEDLG                  33106
#define ID_ZENGSHOUBAO                  33107
#define ID_LABEL                        33108
#define ID_BUTTON33109                  33109
#define ID_ACTIVE_REMARK                33110
#define ID_CREDITMODIFY                 33111
#define IDM_CARDOPENCONSUME             33112
#define IDM_DIANKA                      33115
#define ID_RE_BILLING                   33117
#define ID_SEAT_COMPUTER_MENU           33122
#define IDM_ROOM                        33123
#define ID_LOCK_SCREEN                  33125
#define IDM_READ_CARD                   33126
#define IDM_EXPORTEXCEL                 33129
#define ID_CHOOSECAMERA                 33132
#define IDM_SCAN2_BACK                  33133
#define IDM_SCAN_PASSPORT               33135
#define ID_SEAT_ADDALL                  33136
#define ID_SEAT_DELALL                  33137
#define IDM_ACTIVEMEMBERVIEW            33138
#define IDM_COMPUTERLIST_VIEW           33139
#define IDM_VIEW_OPERATOR               33140
#define ID_33167                        33141
#define IDM_ADD_CASHIER                 33142
#define IDM_ADD_TOILET                  33143
#define IDM_ADD_REFRIGRAETOR            33144
#define IDM_ADD_ENTRANCE                33145
#define IDS_BUNDLETIMELISTHEADER        0xE001
#define IDS_RETURNSTATE                 57346
#define ID_ABOUT                        0xE140
#define ID_EXIT                         0xE141
#define ID_VIEW_TOOLBARS                0xE800
#define ID_TOOL_STATUS                  59393

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        360
#define _APS_NEXT_COMMAND_VALUE         33136
#define _APS_NEXT_CONTROL_VALUE         1551
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
