#pragma once

#include ".\\include\\G2XUser.h"
#include ".\\include\\G2XDef.h"
#include ".\\include\\G2XObject.h"
#include ".\\include\\G2XDrawImpl.h"
#include ".\\include\\GdiDrawMask.h"
#include ".\\include\\GraphicsEx.h"

#include ".\\include\\G2XWnd.h"
#include ".\\include\\AnalyseTextAttribute.h"
#include ".\\include\\G2XImageList.h"
#include ".\\include\\G2XControl.h"
#include ".\\include\\G2XScrollBar.h"
#include ".\\include\\G2XPanel.h"
#include ".\\include\\G2XButton.h"
#include ".\\include\\G2XCheckBox.h"
#include ".\\include\\G2XRadioBox.h"
#include ".\\include\\G2XPictureCtrl.h"
#include ".\\include\\G2XRollText.h"
#include ".\\include\\G2XCalendar.h"
#include ".\\include\\G2XDateCtrl.h"
#include ".\\include\\G2XGridCtrl.h"
#include ".\\include\\G2XLinkButton.h"
#include ".\\include\\G2XSysBtnBar.h"
#include ".\\include\\G2XCaptionBar.h"
#include ".\\include\\G2XFoundationWnd.h"
#include ".\\include\\G2XDialog.h"
#include ".\\include\\G2XStatic.h"
#include ".\\include\\G2XStaticEx.h"
#include ".\\include\\G2XGroupBox.h"
#include ".\\include\\G2XWebPanel.h"
#include ".\\include\\G2XSplitPanel.h"
#include ".\\include\\G2XCalendarWnd.h"
#include ".\\include\\G2XListBox.h"
#include ".\\include\\G2XProgressCtrl.h"
#include ".\\include\\G2XTreeCtrl.h"

#include ".\\include\\GxxListCtrl.h"
#include ".\\include\\G2XCommandbar.h"
#include ".\\include\\G2XDropList.h"
#include ".\\include\\G2XTabPanel.h"
#include ".\\include\\G2XTabCtrl.h"


#include ".\\include\\G2XFoundationWindow.h"
#include ".\\include\\G2XToolTipCtrl.h"
#include ".\\include\\G2XPopupMenu.h"