#if !defined(AFX_HWIDCARD_H__399AE553_93B9_4A6E_A191_A09B4E27F8B9__INCLUDED_)
#define AFX_HWIDCARD_H__399AE553_93B9_4A6E_A191_A09B4E27F8B9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHWIDCard wrapper class

class CHWIDCard : public CWnd
{
protected:
	DECLARE_DYNCREATE(CHWIDCard)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xaa784f0f, 0x90df, 0x44a1, { 0xa3, 0x8d, 0x53, 0x28, 0x13, 0xb5, 0x41, 0xb8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetIDName();
	void SetIDName(LPCTSTR);
	CString GetIDAdrr();
	void SetIDAdrr(LPCTSTR);
	CString GetIDNation();
	void SetIDNation(LPCTSTR);
	CString GetIDNumber();
	void SetIDNumber(LPCTSTR);
	CString GetIDSex();
	void SetIDSex(LPCTSTR);
	CString GetIDSignDate();
	void SetIDSignDate(LPCTSTR);
	CString GetIDBirthday();
	void SetIDBirthday(LPCTSTR);
	CString GetIDTimeLimit();
	void SetIDTimeLimit(LPCTSTR);
	CString GetCarType();
	void SetCarType(LPCTSTR);
	CString GetPassportNo();
	void SetPassportNo(LPCTSTR);
	CString GetImgFileName();
	void SetImgFileName(LPCTSTR);
	BOOL GetSaveLittleImg();
	void SetSaveLittleImg(BOOL);
	BOOL GetAutoCheckPaper();
	void SetAutoCheckPaper(BOOL);
	CString GetIDPhotoFileName();
	void SetIDPhotoFileName(LPCTSTR);

// Operations
public:
	void HWCalibrate();
	BOOL HWScan(short CardType);
	BOOL HWInitScanner(LPCTSTR ImgFileName);
	void HWEndScan();
	BOOL HWUserdefinedScan4(short iScanType, short iScanDpi, short usScanStartX, short usScanStartY, short usScanWidth, short usScanHeight);
	CString HWGetImageContent();
	BOOL HWClearTempFile();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HWIDCARD_H__399AE553_93B9_4A6E_A191_A09B4E27F8B9__INCLUDED_)
